title: Personal-blog
description: Establish a personal blog, share learning IT knowledge, to aspire to the other shore.
google_analytics: 
show_downloads: true
theme: jekyll-theme-dinky

gems:
  - jekyll-mentions
